### ISSUE TITLE
prominence presentAudio=False 

### ISSUE THREAD

**Issue by jah238** [timmahrt/LMEDS#3]
When the presentAudio false is set to False on a prominence page, it fails to advance.

**Comment by timmahrt** [comment]
Thanks for the heads up!  This should be fixed now in version 2.5.5: https://github.com/timmahrt/LMEDS/releases/tag/v2.5.5

Please let me know if it resolves your issue.

**Comment by jah238** [comment]
Thanks, Tim!  We thought it was fixed (it was working great on the local server), but now that we're upload it to nearlyfreespeech we get a 500 error.  I checked permissions for .cgi file, output folder and individual sequences folder.

**Comment by timmahrt** [comment]
Do you get a 500 error right away?  I just tried uploading a copy to a fresh directory in nearlyfreespeech and also got a 500 error.  I changed the permissions of the .cgi file to '665' and that resolved the issue. It's the only thing I had to configure to get the login screen to render.

**Comment by jah238** [comment]
Login screen renders, but I can't progress from there.

**Comment by timmahrt** [comment]
You should have a folder `tests/<<experiment_name>>/output/<<sequence_output_name>>/` and it needs to have permissions `777`. I had to make that change to be able to progress.

**Comment by timmahrt** [comment]
It that still doesn't work and you're comfortable doing so, you can send me your whole lmeds folder (with just a representative sample of your test folder) and I can try to run it on my account.

**Comment by jah238** [comment]
I double-checked and that directory had the right permissions also.  Thanks for the offer to share!  Here's a copy with all but a few of the items removed.  https://drive.google.com/file/d/13u-VjVEXn5eBUL5swB4E8vLjbryhZmZs/view?usp=sharing

**Comment by timmahrt** [comment]
I've requested permissions to access it.

One more question: did you overwrite your previous /lmeds directory or did you start from a clean folder.  If you overwrote your previous /lmeds directory, its possible that there is some conflict between old and new files that causes the problem. It might be worth trying from a clean folder, if you haven't yet already.

**Comment by timmahrt** [comment]
After changing the permissions on the cgi file and the output directory, I was able to run the experiment snippet until the end. Hmmmm

**Comment by timmahrt** [comment]
Can you try using this sequence file?
https://drive.google.com/file/d/1pTDUQ0bXmWICkGGZpOA4KfvvIXnuC78a/view?usp=sharing

You may need to adapt it a bit for your experiment.  With this file, if there are any errors when running an experiment, they will be dumped to `/tmp/lmeds.log`.  Trying this out with some intentionally place errors, I was able to see them in that log file on my server.

In the logs folder, there was already a log file I hadn't seen before which had some error information that probably would have been useful if I had checked it at the time (it was called `nfsn_cgi.log`).

**Comment by jah238** [comment]
It works!  What's different?

**Comment by timmahrt** [comment]
The new sequence file works?  It shouldn't have fixed anything, I just added some logging to it.

I guess that either your original cgi file was modified and broke things or the previous permission error was cached and still being displayed even though the root problem was resolved.  🤔   

In either case, I'm glad the issue is resolved.  😌
